---
title: "eds212-day5-comp1"
format: 
  html: 
    code-fold: true
    code-summary: "show me the code!"
#controls the visualization of how the document is shown
editor: visual
execute: 
  echo: true
  #echo controls whether the code shows up. false hides the code, true shows the code
  warning: false
  #warning controls the messages, false hides the messages, true shows the messages
---

```{r}
library(tidyverse)
```

# Explore starwars dataset
-   look at the first 6 lines of starwars
-   find the dimensions of starwars
-   make a histogram of character heights
-   make a scatterplot of height vs weight
```{r}
#look at first 6 lines
head(starwars)
```
```{r}
#find the dimensions of starwars
dim(starwars)
```
```{r}
#make a histogram of character heights
height_histogram <- ggplot(data = starwars, aes(x = height)) + geom_histogram()
height_histogram
```
```{r}
#make a scatterplot of height vs weight
height_weight_scatterplot <- ggplot(data = starwars, aes(x = height, y = mass, color = "pink")) + 
  geom_point() + 
  labs(x = "Height", 
       y = "Weight", 
       title = "Height vs Weight") + 
  theme_light()
height_weight_scatterplot
```

# Calculate summary statistics
## Use mean() function to find means.
## Use sd() function to find standard deviations
```{r}
mean_height_test <- mean(starwars)
#this does not work since there are a bunch of categories it can pull from
mean_height <- mean(starwars$height, na.rm = TRUE)
#this will show me the mean of the characters heights in starwars
  #na.rm keeps or removes the non exsisting values. true will remove, false will keep
mean_height
```
## Find and store the standard deviation of character heights
```{r}
sd_height <- sd(starwars$height, na.rm = TRUE)
sd_height
```








